### ISSUE TITLE
Hostname string being passed to function that takes IP as arg

### ISSUE THREAD

**Issue by hotpeppersec** [wwce/Assassin#24]
add try/catch & debugging to diagnose issue

Here a FQDN is being passed to the check private IP function instead of an IP address:
```
2020-04-10 12:28:52,614 - assassinLogger - DEBUG - Processing host: login.gslb.paloaltonetworks.com
2020-04-10 12:28:52,614 - assassinLogger - DEBUG - Check for non prod string in hostname: login.gslb.paloaltonetworks.com
2020-04-10 12:28:52,821 - assassinLogger - DEBUG - Create report for IP: login.inap.gslb.paloaltonetworks.com.
2020-04-10 12:28:52,821 - assassinLogger - DEBUG - Check private IP: login.inap.gslb.paloaltonetworks.com.
```

```
Processing host: login.gslb.paloaltonetworks.com
Traceback (most recent call last):
  File "assassin.py", line 113, in <module>
    main()
  File "assassin.py", line 100, in main
    report_ip(report, domain, ip, summary)
  File "/app/assassin/lib/reporting.py", line 147, in report_ip
    if checkPrivate(ip) or checkReserved(ip):
  File "/app/assassin/lib/helper_functions.py", line 148, in checkPrivate
    if (ipaddress.ip_address(ip).is_private):
  File "/usr/local/lib/python3.8/ipaddress.py", line 53, in ip_address
    raise ValueError('%r does not appear to be an IPv4 or IPv6 address' %
ValueError: 'login.inap.gslb.paloaltonetworks.com.' does not appear to be an IPv4 or IPv6 address
```

**Comment by hotpeppersec** [comment]
Created this function to check IP addresses as valid:

```
def validate_ip(ip):
    '''
    Verify IP address is valid
    '''
    try:
        ipaddress.ip_address(ip)
    except ValueError as e:
        logger.debug('Failed validate_ip: %s' % (ip))
        logger.debug('Exception: %s' % e)
        return False
    logger.debug('Successful validate_ip: %s' % (ip))
    return True
```
