### ISSUE TITLE
reporting.py fails with KeyError 'sslexpired'

### ISSUE THREAD

**Issue by lknittig-panw** [wwce/Assassin#31]
no data in assassin.log related to this processing host.  output from console. 

Processing host: santaclara.paloaltonetworks.com
Traceback (most recent call last):
  File "assassin.py", line 100, in <module>
    main()
  File "assassin.py", line 90, in main
    report_shodan(report, domain, ip, host, hosts, shodan, summary)
  File "/app/assassin/lib/reporting.py", line 562, in report_shodan
    summary['sslexpired'] += 1
KeyError: 'sslexpired'

**Comment by hotpeppersec** [comment]
I am seeing a similar error (but different host maybe?). I found a fault in the logic that sets the key index to zero the first time it is used. 

```
Processing host: ciosummit2018.paloaltonetworks.com
Traceback (most recent call last):
  File "assassin.py", line 100, in <module>
    main()
  File "assassin.py", line 90, in main
    report_shodan(report, domain, ip, host, hosts, shodan, summary)
  File "/app/assassin/lib/reporting.py", line 562, in report_shodan
    summary['sslexpired'] += 1
KeyError: 'sslexpired'
root@assassin:/app/assassin# tail /var/log/secops/assassin.log 
[2020-04-16 17:54:35,918] [reporting.py:223 - report_shodan() - MainProcess] DEBUG - shodan
[2020-04-16 17:54:35,919] [reporting.py:238 - report_shodan() - MainProcess] DEBUG - Increment service summary counter
[2020-04-16 17:54:35,919] [reporting.py:268 - report_shodan() - MainProcess] DEBUG - Writing service data: HTTP/1.1 200 OK
Date: Tue, 14 Apr 2020 12:56:26 GMT
Server: Apache
X-Frame-Options: SAMEORIGIN
Content-Length: 40
Content-Type: text/html; charset=utf-8

```
